---
title: "R Markdown to Markdown conversion"
author: "Sanne Govaert"
date: "`r Sys.Date()`"
output: html_document
---

## Setup

### Select package

For what package do you want to (re)generate the documentation? See `vignettes.yml` for settings:

```{r}
package <- "gcube"
overwrite_b3verse <- FALSE
```

### Load libraries

```{r}
library(yaml)
library(purrr)
library(here)
```

### Install all b3verse packages

```{r}
if (overwrite_b3verse) {
  pkgs <- rownames(available.packages(repos = "https://b-cubed-eu.r-universe.dev"))  
  install.packages(pkgs, repos = c("https://b-cubed-eu.r-universe.dev", "https://cloud.r-project.org", "https://bioc.r-universe.dev"))
}
```

### Read yaml

```{r}
yaml <- yaml::read_yaml(here::here("src", "rmd_to_md", "vignettes.yml"))
```

## Create documentation

### Select yaml

```{r}
yaml_package <- yaml[[package]]
```

### Install the packages used in the Rmd files

```{r}
dependencies <- unlist(
  purrr::map(yaml_package, function(item) {
    if (!is.null(item$dependencies)) {
      unlist(strsplit(item$dependencies, "[ ,]+"))
    } else {
      NULL
    }
  })
)

purrr::map(unique(dependencies), ~ rlang::check_installed(.x))
```

### Convert vignettes

```{r}
md_dir <- here::here("src", "content", "docs", "software", package)
fig_dir <- here::here("public", "software", package)
fig_url_dir <- paste0("/software/", package, "/")

purrr::walk(
  yaml_package,
  ~ b3doc::rmd_to_md(
    .x$source,
    md_dir,
    fig_dir,
    fig_url_dir,
    title = purrr::pluck(.x, "title", .default = NULL),
    sidebar_label = purrr::pluck(.x, "sidebar_label", .default = NULL),
    sidebar_order = which(purrr::map_chr(yaml_package, "source") == .x$source),
    replace = unlist(purrr::pluck(.x, "replace", .default = NULL))
  )
)
```
